apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-service-deployment
  labels:
    app: ai-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-service
  template:
    metadata:
      labels:
        app: ai-service
    spec:
      containers:
      - name: ai-service
        image: msalmannaqvi/ai-service:latest
        ports:
        - containerPort: 5001
        env:
        - name: APP_VERSION
          value: "0.1.0"
        - name: PYTHON_VERSION
          value: "3.12.4"
        - name: PYTHON_PIP_VERSION
          value: "24.0"
        - name: LANG
          value: "C.UTF-8"
        command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5001"]

---
apiVersion: v1
kind: Service
metadata:
  name: ai-service-service
  labels:
    app: ai-service
spec:
  type: LoadBalancer
  ports:
  - port: 5001
    targetPort: 5001
    protocol: TCP
  selector:
    app: ai-service
