apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-deployment
  labels:
    app: order-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: msalmannaqvi/order-service:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_VERSION
          value: "18.20.4"
        - name: YARN_VERSION
          value: "1.22.19"
        - name: APP_VERSION
          value: "0.1.0"

---
apiVersion: v1
kind: Service
metadata:
  name: order-service-service
  labels:
    app: order-service
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: order-service
