apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-admin-deployment
  labels:
    app: store-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store-admin
  template:
    metadata:
      labels:
        app: store-admin
    spec:
      containers:
      - name: store-admin
        image: msalmannaqvi/store-admin:latest
        ports:
        - containerPort: 80
        - containerPort: 8081
        # Uncomment the following lines if you need to set any specific environment variables
        # env:
        # - name: SOME_ENV_VAR
        #   value: "value"
---
apiVersion: v1
kind: Service
metadata:
  name: store-admin-service
  labels:
    app: store-admin
spec
