apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-front-deployment
  labels:
    app: store-front
spec:
  replicas: 2
  selector:
    matchLabels:
      app: store-front
  template:
    metadata:
      labels:
        app: store-front
    spec:
      containers:
      - name: store-front
        image: msalmannaqvi/store-front:latest
        ports:
        - containerPort: 80
        - containerPort: 8080
        env:
        - name: NGINX_VERSION
          value: "1.26.2"
        - name: PKG_RELEASE
          value: "1"
        - name: DYNPKG_RELEASE
          value: "2"
        - name: APP_VERSION
          value: "0.1.0"

---
apiVersion: v1
kind: Service
metadata:
  name: store-front-service
  labels:
    app: store-front
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: store-front
